[pytest]
# Indique le fichier settings de ton projet Django
DJANGO_SETTINGS_MODULE = config.settings

# Modèles de noms de fichiers recherchés pour les tests
python_files = tests.py test_*.py *_tests.py

# Options par défaut :
# --reuse-db : Réutilise la BDD de test si aucune migration n'a changé
# --cov=apps : Calcule la couverture sur ton dossier apps (users, courses, quizzes, etc.)
# --cov-report=term-missing : Affiche les lignes non testées directement dans le terminal
addopts = --reuse-db --cov=apps --cov-report=term-missing

# Warnings tiers (reportlab) — hors de notre contrôle
filterwarnings =
    ignore:ast.NameConstant is deprecated:DeprecationWarning:reportlab.lib.rl_safe_eval
