# Generated by Django 6.0.7 on 2026-07-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a activé son compte via le lien envoyé par email."),
        ),
    ]
