# Generated by Django 6.0.7 on 2026-07-24 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre_fichier', models.CharField(max_length=255, verbose_name='Titre / Nom du contenu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Contenu',
                'verbose_name_plural': 'Contenus',
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('duree_estimee', models.PositiveIntegerField(default=10, help_text='Durée estimée en minutes', verbose_name='Durée (min)')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ContenuDocument',
            fields=[
                ('contenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.contenu')),
                ('fichier', models.FileField(upload_to='courses/documents/', verbose_name='Fichier document')),
                ('format', models.CharField(help_text='Ex: PDF, DOCX', max_length=10, verbose_name='Format du fichier')),
            ],
            options={
                'verbose_name': 'Contenu Document',
                'verbose_name_plural': 'Contenus Documents',
            },
            bases=('courses.contenu',),
        ),
        migrations.CreateModel(
            name='ContenuSCORM',
            fields=[
                ('contenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.contenu')),
                ('package_url', models.FileField(upload_to='courses/scorm/', verbose_name='Archive SCORM (ZIP)')),
                ('standard', models.CharField(default='SCORM 1.2', max_length=50, verbose_name='Standard')),
                ('version', models.CharField(default='1.2', max_length=20, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Contenu SCORM',
                'verbose_name_plural': 'Contenus SCORM',
            },
            bases=('courses.contenu',),
        ),
        migrations.CreateModel(
            name='ContenuVideo',
            fields=[
                ('contenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.contenu')),
                ('url_stream', models.URLField(verbose_name='URL du flux vidéo')),
                ('duree', models.PositiveIntegerField(help_text='Durée en secondes', verbose_name='Durée (s)')),
                ('statut_encodage', models.CharField(choices=[('EN_COURS', "En cours d'encodage"), ('PRET', 'Prêt'), ('ECHEC', 'Échec de conversion')], default='PRET', max_length=20, verbose_name="Statut d'encodage")),
            ],
            options={
                'verbose_name': 'Contenu Vidéo',
                'verbose_name_plural': 'Contenus Vidéos',
            },
            bases=('courses.contenu',),
        ),
        migrations.AddField(
            model_name='contenu',
            name='lecon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contenu', to='courses.lecon', verbose_name='Leçon'),
        ),
        migrations.AddField(
            model_name='lecon',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='courses.module', verbose_name='Module'),
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('profil_cible', models.CharField(choices=[('EDUCATEUR', 'Éducateur'), ('FORCES_ORDRE', "Forces de l'ordre"), ('MAGISTRAT', 'Magistrat'), ('ASSISTANT_SOCIAL', 'Assistant social'), ('AUTRE', 'Autre')], default='EDUCATEUR', max_length=50, verbose_name='Profil Cible')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20, verbose_name='Statut de publication')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcours_crees', to=settings.AUTH_USER_MODEL, verbose_name='Formateur référent')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'ordering': ['ordre', '-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.parcours', verbose_name='Parcours'),
        ),
    ]
