# Generated by Django 6.0.7 on 2026-08-08 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_contenutexte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(blank=True, choices=[('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document')], default='', max_length=20, verbose_name='Type de source')),
                ('transcription', models.TextField(blank=True, default='', verbose_name='Transcription / texte extrait')),
                ('resume', models.TextField(blank=True, default='', verbose_name='Résumé')),
                ('model_name', models.CharField(blank=True, default='', max_length=80)),
                ('statut', models.CharField(choices=[('NON_COMMENCE', 'Non commencé'), ('EN_COURS', 'En cours'), ('PRET', 'Prêt'), ('ERREUR', 'Erreur')], default='NON_COMMENCE', max_length=20)),
                ('erreur', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_resume', to='courses.lecon', verbose_name='Leçon')),
            ],
            options={
                'verbose_name': 'Résumé IA',
                'verbose_name_plural': 'Résumés IA',
            },
        ),
    ]
