# Generated by Django 6.0.7 on 2026-08-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_contenu_resume_ia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContenuResume',
        ),
    ]
