# Generated by Django 6.0.7 on 2026-08-08 23:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_contenutexte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('profil_cible', models.CharField(choices=[('EDUCATEUR', 'Éducateur'), ('FORCES_ORDRE', "Forces de l'ordre"), ('MAGISTRAT', 'Magistrat'), ('ASSISTANT_SOCIAL', 'Assistant social'), ('AUTRE', 'Autre')], default='EDUCATEUR', max_length=50, verbose_name='Profil cible')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('url_visio', models.URLField(help_text='Lien Zoom, Google Meet, Teams, Jitsi, etc.', max_length=500, verbose_name='Lien visioconférence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_live', to=settings.AUTH_USER_MODEL, verbose_name='Formateur')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_live', to='courses.parcours', verbose_name='Parcours lié')),
            ],
            options={
                'verbose_name': 'Session live',
                'verbose_name_plural': 'Sessions live',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PresenceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_join', models.DateTimeField(auto_now_add=True, verbose_name='Date de join')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='live_sessions.sessionlive', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Présence session',
                'verbose_name_plural': 'Présences sessions',
                'ordering': ['-date_join'],
                'unique_together': {('session', 'apprenant')},
            },
        ),
    ]
