# Generated by Django 6.0.7 on 2026-08-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlive',
            name='room_name',
            field=models.CharField(blank=True, default='', help_text='Salle vidéo intégrée générée automatiquement', max_length=120, unique=True, verbose_name='Identifiant de salle'),
        ),
        migrations.AlterField(
            model_name='sessionlive',
            name='url_visio',
            field=models.URLField(blank=True, default='', help_text='Conservé pour compatibilité — la visio est désormais intégrée.', max_length=500, verbose_name='Lien externe (obsolète)'),
        ),
    ]
