# Generated by Django 6.0.7 on 2026-08-08 23:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0002_integrated_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPeer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peer_id', models.CharField(db_index=True, max_length=64)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_moderator', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_peers', to='live_sessions.sessionlive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_room_peers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pair WebRTC',
                'verbose_name_plural': 'Pairs WebRTC',
                'ordering': ['-last_seen'],
                'unique_together': {('session', 'peer_id')},
            },
        ),
        migrations.CreateModel(
            name='SignalMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_peer_id', models.CharField(db_index=True, max_length=64)),
                ('to_peer_id', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='live_sessions.sessionlive')),
            ],
            options={
                'verbose_name': 'Signal WebRTC',
                'verbose_name_plural': 'Signals WebRTC',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'to_peer_id', 'consumed'], name='live_sessio_session_e3d008_idx')],
            },
        ),
    ]
