# Generated by Django 6.0.7 on 2026-08-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0003_webrtc_native'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompeer',
            name='camera_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roompeer',
            name='mic_on',
            field=models.BooleanField(default=True),
        ),
    ]
