# Generated by Django 6.0.7 on 2026-07-24 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('NON_COMMENCE', 'Non commencé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='NON_COMMENCE', max_length=20, verbose_name='Statut')),
                ('temps_passe', models.PositiveIntegerField(default=0, help_text='Temps passé en secondes', verbose_name='Temps passé (s)')),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='courses.lecon', verbose_name='Leçon')),
            ],
            options={
                'verbose_name': 'Progression',
                'verbose_name_plural': 'Progressions',
                'unique_together': {('apprenant', 'lecon')},
            },
        ),
    ]
