# Generated by Django 6.0.7 on 2026-08-08 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0004_favori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteJournaliere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('secondes', models.PositiveIntegerField(default=0, help_text="Secondes d'apprentissage cumulées ce jour", verbose_name='Temps (s)')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_journalieres', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
            ],
            options={
                'verbose_name': 'Activité journalière',
                'verbose_name_plural': 'Activités journalières',
                'ordering': ['-date'],
                'unique_together': {('apprenant', 'date')},
            },
        ),
    ]
